id: IC74AA01F
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:50:22.020313
last_modified: 2023-02-09 14:50:22.020429
source_metadata:
  title: 'PP: Ratnaguṇasaṃcayagāthā'
  language: en
bases:
  1F2C:
    base_file: 1F2C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
